#!/usr/bin/env python3
import os
import sys
from pathlib import Path

if len(sys.argv) != 2:
    print("Usage: %s <directory>" % sys.argv[0])
    sys.exit(1)

target_directory = Path(sys.argv[1])
error_files = [file for file in target_directory.iterdir() if file.suffix == ".err"]
test_files = [target_directory/f'{file.stem.split(".")[0]}.ktest' for file in error_files]

for test_file in test_files:
    os.system(f"ktest-tool {test_file}")
